### ISSUE TITLE
Code explanation

### ISSUE THREAD

**Issue by rr32** [bobthebutcher/viptela#5]
Hello, could anyone please explain what this line does ?

https://github.com/bobthebutcher/viptela/blob/232ef08f511d761907ede57d6068074aa27c9c62/viptela/constants.py#L92

Thanks.
Regards,

Rahenda

**Comment by bwks** [comment]
Hi Rahenda,

Apologies, I did not see this issue until just now. This merges the two dicts `HTTP_SUCCESS_CODES and HTTP_ERROR_CODES`

It was probably written this way because we originally wanted to support python2 as well as python3 if I was to refactor this library to utilise only 3.6+ I would do this instead 
```
HTTP_RESPONSE_CODES = {**HTTP_SUCCESS_CODES, **HTTP_ERROR_CODES}
```

I will close this issue
